name: authsignal_example
description: Example app demonstrating Authsignal Flutter SDK usage
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.2.2 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  authsignal_flutter:
    path: ../
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

