name: authsignal_flutter
description: "The Authsignal Flutter SDK for Passkeys, Push, QR, and In-App Authentication"
version: 2.1.0
homepage: "https://github.com/authsignal/authsignal-flutter"

environment:
  sdk: ">=3.2.2 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  authsignal_flutter_platform_interface:
    path: authsignal_flutter_platform_interface
  authsignal_flutter_web:
    path: authsignal_flutter_web
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.authsignal.authsignal_flutter
        pluginClass: AuthsignalPlugin
      ios:
        pluginClass: AuthsignalPlugin
      web:
        default_package: authsignal_flutter_web
